# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/james/video

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/james/video

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/video/CMakeFiles /home/james/video/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/video/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ttyvideo

# Build rule for target.
ttyvideo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttyvideo
.PHONY : ttyvideo

# fast build rule for target.
ttyvideo/fast:
	$(MAKE) -f CMakeFiles/ttyvideo.dir/build.make CMakeFiles/ttyvideo.dir/build
.PHONY : ttyvideo/fast

#=============================================================================
# Target rules for targets named handle

# Build rule for target.
handle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 handle
.PHONY : handle

# fast build rule for target.
handle/fast:
	$(MAKE) -f CMakeFiles/handle.dir/build.make CMakeFiles/handle.dir/build
.PHONY : handle/fast

handle.o: handle.c.o

.PHONY : handle.o

# target to build an object file
handle.c.o:
	$(MAKE) -f CMakeFiles/handle.dir/build.make CMakeFiles/handle.dir/handle.c.o
.PHONY : handle.c.o

handle.i: handle.c.i

.PHONY : handle.i

# target to preprocess a source file
handle.c.i:
	$(MAKE) -f CMakeFiles/handle.dir/build.make CMakeFiles/handle.dir/handle.c.i
.PHONY : handle.c.i

handle.s: handle.c.s

.PHONY : handle.s

# target to generate assembly for a file
handle.c.s:
	$(MAKE) -f CMakeFiles/handle.dir/build.make CMakeFiles/handle.dir/handle.c.s
.PHONY : handle.c.s

ttyvideo.o: ttyvideo.c.o

.PHONY : ttyvideo.o

# target to build an object file
ttyvideo.c.o:
	$(MAKE) -f CMakeFiles/ttyvideo.dir/build.make CMakeFiles/ttyvideo.dir/ttyvideo.c.o
.PHONY : ttyvideo.c.o

ttyvideo.i: ttyvideo.c.i

.PHONY : ttyvideo.i

# target to preprocess a source file
ttyvideo.c.i:
	$(MAKE) -f CMakeFiles/ttyvideo.dir/build.make CMakeFiles/ttyvideo.dir/ttyvideo.c.i
.PHONY : ttyvideo.c.i

ttyvideo.s: ttyvideo.c.s

.PHONY : ttyvideo.s

# target to generate assembly for a file
ttyvideo.c.s:
	$(MAKE) -f CMakeFiles/ttyvideo.dir/build.make CMakeFiles/ttyvideo.dir/ttyvideo.c.s
.PHONY : ttyvideo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ttyvideo"
	@echo "... handle"
	@echo "... handle.o"
	@echo "... handle.i"
	@echo "... handle.s"
	@echo "... ttyvideo.o"
	@echo "... ttyvideo.i"
	@echo "... ttyvideo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

